spring.application.name=MulyaMessenger

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.sql.init.mode=always
spring.jpa.properties.hibernate.show_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.main.allow-circular-references=true
spring.jpa.open-in-view=false


spring.datasource.url=jdbc:h2:file:./data/Websockets
spring.datasource.username=spring
spring.datasource.password=vish@123

spring.datasource.driverClassName=org.h2.Driver

logging.level.root=INFO
logging.level.com.DBMapping=DEBUG



server.address=0.0.0.0
server.port=8081
